import './globals.css'
import { Inter, Anton, Fjalla_One} from 'next/font/google'


const inter = Inter({ subsets: ['latin'], variable: '--font-inter' })


const anton = Anton({
    weight: "400",
    subsets:  ["latin"],
    variable: '--font-anton',
})

const fjalla_one = Fjalla_One({
  weight: "400",
  subsets:  ["latin"],
  variable: '--font-fjalla',
})

export const metadata = {
  title: 'WebDevConsulting',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {



  return (
    <html lang="en" className='scroll-smooth'>
      <body className={`${inter.variable} ${anton.variable} ${fjalla_one.variable}`} >{children}</body>
    </html>
  )
}
